---
title: "Fungicida"
format: html
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = F, warning = FALSE, message = FALSE)
```

```{r }
library(tidyverse) 
library(rio)
library(huxtable)
library(skimr)
library(huxtable)
# library(patchwork)
# library(lme4)
# library(nlme)
# library(emmeans)
# library(multcomp)
# library(performance)

conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflict_prefer("select", "dplyr")

theme_set(theme_bw(base_size = 12)) 
```

```{r}
fungi_raw <- import("data/Planilla Girasol 2023.xlsx", sheet="Fungicida") %>% 
  janitor::clean_names()
```


```{r}
# skim( fungi_raw)
```


```{r}
hum_recibo <- 11
bonif <- 42

fungi_raw %>% 
     mutate(across(c("nombre_tratamiento", "sitio"), 
                   ~stringi::stri_trans_general(
                     #pasar a mayusculas y sacar puntos
                     str_to_upper(gsub(',', '\\.', 
                                       # sacar espacios antes-desp
                                       str_trim(
                                         str_replace_all(., fixed(" "), "_")
                                       ))), "Latin-ASCII"))) %>% 
  # select(rendimiento, humedad_a_cosecha_percent, mat_grasa_mtra_limpia_sss) 
   mutate(
     agua = rendimiento*humedad_a_cosecha_percent/100,
     rinde_seco = rendimiento - agua, 
     rinde_bonif = rinde_seco * (1 + (mat_grasa_mtra_limpia_sss - bonif) * 2/100),
     rinde_final_11 = rinde_bonif*(1+hum_recibo/100)
         )->fungi_dat 

# dat %>% 
#   select(rendimiento, humedad_a_cosecha_percent, mat_grasa_mtra_limpia_sss,
#          agua,rinde_seco,rinde_bonif, rinde_final_11) 
```


```{r}
fungi_dat %>% 
  ggplot() +
  aes(x=sitio, y=rendimiento, col=nombre_tratamiento)+
  geom_point() + 
  stat_summary(fun="mean", geom = "crossbar", width=.2) + 
  stat_summary(fun=mean, aes(label=round(after_stat(y))), geom="text", size=3, vjust=-.5) + 
  coord_flip()+ 
  labs(col="")
```
```{r}
fungi_dat %>% 
  ggplot() +
  aes(x=sitio, y=rinde_bonif, col=nombre_tratamiento)+
  geom_point() + 
  stat_summary(fun="mean", geom = "crossbar", width=.2) + 
  stat_summary(fun=mean, aes(label=round(after_stat(y))), geom="text", size=3, vjust=-.5) + 
  coord_flip()+ 
  labs(col="")
```

```{r}
fungi_dat %>% #names %>% sort 
  filter(sitio!="RIVERA") %>% 
  ggplot() +
  aes(x=sitio, y=mat_grasa_mtra_limpia_sss, col=nombre_tratamiento)+
  geom_point() + 
  stat_summary(fun="mean", geom = "crossbar", width=.2) + 
  stat_summary(fun=mean, aes(label=round(after_stat(y))), geom="text", size=3, vjust=-.5) + 
  coord_flip()+ 
  labs(col="")
```

```{r}
fungi_dat %>% #names %>% sort 
  filter(sitio=="RIVERA") %>% 
  ggplot() +
  aes(x=sitio, y=mat_grasa_mtra_limpia_sss, col=nombre_tratamiento)+
  geom_point() + 
  stat_summary(fun="mean", geom = "crossbar", width=.2) + 
  stat_summary(fun=mean, aes(label=round(after_stat(y))), geom="text", size=3, vjust=-.5) + 
  coord_flip()+ 
  labs(col="")
```

